### ISSUE TITLE
Wrong geocoordinates

### ISSUE THREAD

**Issue by jnehring** [dkt-projekt/e-NLP#8]
This API Call

```
curl -X POST -H "Content-Type: text/plain" -H "Cache-Control: no-cache" -H "Postman-Token: 78f58c5c-45a4-985c-7cea-d5079830226a" -d 'The summer of 2016 is not very hot in Berlin. Wolfgang Rossi, weather reports of the German Tagesschau, added that the summer of 1983 was much better.' "http://dev.digitale-kuratierung.de/api/e-nlp/namedEntityRecognition?language=en&analysis=ner&models=ner-wikinerEn_LOC;ner-wikinerEn_ORG;ner-wikinerEn_PER"`
```

produces among stuff

```
<http://dkt.dfki.de/documents/#char=0,150>
        a                        nif:Context , nif:String , nif:RFC5147String ;
        dktnif:averageLatitude   "52.516666666666666"^^xsd:double ;
        dktnif:averageLongitude  "13.383333333333333"^^xsd:double ;
        dktnif:standardDeviationLatitude
                "0.0"^^xsd:double ;
        dktnif:standardDeviationLongitude
                "0.0"^^xsd:double ;
        nif:beginIndex           "0"^^xsd:nonNegativeInteger ;
        nif:endIndex             "150"^^xsd:nonNegativeInteger ;
        nif:isString             "The summer of 2016 is not very hot in Berlin. Wolfgang Rossi, weather reports of the German Tagesschau, added that the summer of 1983 was much better."^^xsd:string .
```

I wonder why latitude and longitude 0 are attached to the NIF document. It is not even attached to the annotation but to the whole document. It looks like a bug to me.

**Comment by PeterBourgonje** [comment]
I suspect (in the complete NIF) there is one location recognized (e.g. Berlin, the co-ordinates match the spot right in front of the Russian embassy at Unter den Linden :). The 0 values are for standard deviation (because the average is based on one value), not for latitude or longitude itself. 
This annotation is added at the document level for geolocation, because we want this to work on a whole document. Standard deviation is used to get an idea of the 'spread' over the globe (e.g. we do not want to pinpoint a document speaking of both China and Chili to be shown on the map as somewhere in, say, Nigeria, but want to have information that allows to visualize that the geographical 'spread' of the document is large).

**Comment by jnehring** [comment]
ah i see. so it is not a bug. thanks for investigating.
